### ISSUE TITLE
The Repo should provide a better readme

### ISSUE THREAD

**Issue by davidblumer** [Devnetik/react-native-button#3]

**Comment by maluramichael** [comment]
Would be nice when the readme looks like in our other repos. https://github.com/Devnetik/react-native-slide-view

**Comment by hyeinu** [comment]
Hi maluramichael, just wondering have you published this package on npm or are you still waiting to do so? I was trying to install and use it to get a better sense of how to write the README/example section.

**Comment by maluramichael** [comment]
Hey @hyeinu no the react-native-button on npm is not this repo. I need another name then i will publish it to npm.

**Comment by maluramichael** [comment]
#5 fixed this
